---
name: Sanity test testing farm github runners
on:
  push:
  pull_request:
jobs:
  sanity:
    runs-on: testing-farm
    steps:
        - name: Run testing-farm sanity test
          env:
            TESTING_FARM_API_TOKEN: ${{ secrets.TESTING_FARM_API_TOKEN }}
          run: |
            testing-farm request --compose Fedora-40 --plan /testing-farm/sanity --git-url https://gitlab.com/testing-farm/tests

        - name: Run testing-farm reservation test
          env:
            TESTING_FARM_API_TOKEN: ${{ secrets.TESTING_FARM_API_TOKEN }}
          run: |
            testing-farm reserve --compose Fedora-40 --duration 1 <<< "exit" |& tee output
            ssh -oUserKnownHostsFile=/dev/null $(grep -Eo root@[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ output) return2testingfarm
